### ISSUE TITLE
U-Boot prompt not reached

### ISSUE THREAD

**Issue by xypron** [hkominos/ENEA_PicoCluster#1]
I used your scripts to compile U-Boot and copied it the SD card of the Macchiatobin.

I only reached

```
BootROM - 2.03                                                                                                                                                                                          
Starting CP-0 IOROM 1.07                                                                                                                                                                                
Booting from SD 0 (0x29)                                                                                                                                                                                
Found valid image at boot postion 0x002                                                                                                                                                                 
lNOTICE:  Starting binary extension                                                                                                                                                                     
NOTICE:  Gathering DRAM information                                                                                                                                                                     
mv_ddr: mv_ddr-armada-17.06.1-g47f4c8b-dirty (Oct 15 2017 - 01:08:50)                                                                                                                                   
mv_ddr: completed successfully 
```

The U-Boot prompt never showed up. Did you have more success?

**Comment by alexandruavadanii** [comment]
Hi,
This is how our boot log looks.

> BootROM - 2.03
> Starting CP-1 IOROM 1.07
> Booting from SPI NOR flash 1 (0x32)
> Found valid image at boot postion 0x000
> lNOTICE:  Starting binary extension
> NOTICE:  Gathering DRAM information
> mv_ddr: mv_ddr-armada-17.06.1-g47f4c8b (Sep 27 2017 - 11:55:40)
> mv_ddr: completed successfully
> NOTICE:  Booting Trusted Firmware
> NOTICE:  BL1: v1.3(release):armada-17.06.2:297d68f
> NOTICE:  BL1: Built : 11:55:45, Sep 27 2017
> NOTICE:  BL1: Booting BL2
> lNOTICE:  BL2: v1.3(release):armada-17.06.2:297d68f
> NOTICE:  BL2: Built : 11:55:47, Sep 27 2017
> BL2: Initiating SCP_BL2 transfer to SCP
> NOTICE:  Load image to AP MSS
> NOTICE:  Loading MSS image from address 0x4023000 Size 0x504c to MSS at 0xf0580000
> NOTICE:  Done
> NOTICE:  BL1: Booting BL31
> lNOTICE:  BL31: v1.3(release):armada-17.06.2:297d68f
> NOTICE:  BL31: Built : 11:55:49, Sep 27 2017
> l
> 
> U-Boot 2017.03-armada-17.06.3-ga33ecb8 (Sep 27 2017 - 11:55:14 +0200)
> 
> Model: MACCHIATOBin-8040
> Clock:  CPU     1300 [MHz]
>         DDR     800  [MHz]
>         FABRIC  800  [MHz]
>         MSS     200  [MHz]
> DRAM:  16 GiB
> U-Boot DT blob at : 000000007fb12fb8
> EEPROM configuration pattern not detected.
> Comphy chip #0:
> Comphy-0: PEX0
> Comphy-1: PEX0
> Comphy-2: PEX0
> Comphy-3: PEX0
> Comphy-4: SFI
> Comphy-5: SATA1
> Comphy chip #1:
> Comphy-0: SGMII1        1.25 Gbps
> Comphy-1: SATA0
> Comphy-2: USB3_HOST0
> Comphy-3: SATA1
> Comphy-4: SFI
> Comphy-5: SGMII2        3.125 Gbps
> UTMI PHY 0 initialized to USB Host0
> SATA link 0 timeout.
> Target spinup took 0 ms.
> AHCI 0001.0000 32 slots 2 ports 6 Gbps 0x3 impl SATA mode
> flags: 64bit ncq led only pmp fbss pio slum part sxs
> SATA link 0 timeout.
> SATA link 1 timeout.
> AHCI 0001.0000 32 slots 2 ports 6 Gbps 0x3 impl SATA mode
> flags: 64bit ncq led only pmp fbss pio slum part sxs
> PCIE-0: Link down
> MMC:   sdhci@6e0000: 0, sdhci@780000: 1
> SF: Detected w25q32bv with page size 256 Bytes, erase size 4 KiB, total 4 MiB
> Net:   mdio_register: non unique device name 'ethernet@0'
> eth0: mvpp2-0, eth1: mvpp2-3, eth2: mvpp2-4, eth3: mvpp2-5
> Hit any key to stop autoboot:  0

Notice the difference between 'mv_ddr: mv_ddr-armada-17.06.1-g47f4c8b-dirty' vs 'mv_ddr: mv_ddr-armada-17.06.1-g47f4c8b'.
Did you manually edit the contents of the git repos?
May we see a complete u-boot build log (script output) and some details about the board?

**Comment by xypron** [comment]
The issue is not reproducable.
